# Generated by Django 6.0.5 on 2026-06-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.IntegerField(default=0, verbose_name='امتیاز تیم اول')),
                ('score_team2', models.IntegerField(default=0, verbose_name='امتیاز تیم دوم')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مسابقه')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='تیم اول')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='تیم دوم')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='teams.team', verbose_name='برنده')),
            ],
        ),
    ]
