# Generated by Django 6.0.5 on 2026-06-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_match_score_team1_alter_match_score_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='report',
            field=models.TextField(blank=True, verbose_name='گزارش مسابقه'),
        ),
    ]
