# Generated by Django 6.0.5 on 2026-06-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام لیگ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'در حال برگزاری'), ('finished', 'تمام شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='teams.team', verbose_name='تیم')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.tournament', verbose_name='لیگ')),
            ],
            options={
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
