# Generated by Django 6.0.5 on 2026-06-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='competitions.gametype', verbose_name='نوع بازی'),
        ),
    ]
